version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    network_mode: 'host'
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - $PWD/sonrconf:/config
      - /home/reaperfs/Drives/Data/Entertainment/Videos/Series:/tv #optional
      - /home/reaperfs/Drives/Data/Torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    network_mode: 'host'
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - $PWD/radrconf:/config
      - /home/reaperfs/Drives/Data/Entertainment/Videos/Movies:/movies #optional
      - /home/reaperfs/Drives/Data/Torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - $PWD/jackconf:/config
      - /home/reaperfs/Drives/Data/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
