---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin

    container_name: jellyfin

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional

    volumes:
      - /home/reaperfs/Drives/Data/Docker/Jellyfin:/config
      - /home/reaperfs/Entertainment/Videos/Series:/data/tvshows
      - /home/reaperfs/Entertainment/Videos/Movies:/data/movies
      - /home/reaperfs/Drives/Data/Entertainment/Literature/Books:/data/books
      - /home/reaperfs/Drives/Data/Entertainment/Literature/Manga:/data/manga
      - /home/reaperfs/Drives/Data/Entertainment/Literature/Light Novels:/data/ln

    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

    restart: unless-stopped
