---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    network_mode: 'host'
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=reaperfs #optional
      - PASS=fs #optional
      - PEERPORT=9096 #optional
    volumes:
      - /home/reaperfs/Drives/Data/Docker/transmission:/config
      - /home/reaperfs/Drives/Data/Torrents:/downloads
      - /home/reaperfs/Drives/Data/Torrents/watch:/watch
      - /home/reaperfs/Drives/Data/Entertainment/Videos/Movies:/movies
      - /home/reaperfs/Drives/Data/Entertainment/Videos/PostProcessing:/postprocessing
      - /home/reaperfs/Drives/Data/Entertainment/Videos/Series:/tv
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
